### PR TITLE
feat: check for active messages in StatusModule.active

### LINKED ISSUE #19: Using notifier.notify without component nvim
https://github.com/vigoux/notifier.nvim/blob/89e7d10aa9db1e9e55785069a4aa69982d32fcca/lua/notifier/status.lua#L201

If you don't configure any components, message sent through notifier.notify will never be displayed.

Reason I dont want to confiure `vim.notify`, is because **Noice** itself can also be `vim.notify`, which makes it easy to route any messages to different views, like notify or notifier based on filters.

I'm willing to make a PR to make this works, but not sure what the best way would be. Any suggestions?

### PR DESCRIPTION
**Pull request by folke**
Fixes #19

### CODE REVIEW

**Comment by folke** [comment]
My last changes are in here too. Forgot to rebase, but merging woudl still work since that commit is already merged :)

**Comment by vigoux** [comment]
Hum, not sure that it's the proper way of doing it

**Comment by vigoux** [comment]
I added a comment to the issue about that, let's discuss there.

**Comment by vigoux** [comment]
Closing as invalid following the discussion in #19

**Pull request closed without merging**
